### ISSUE TITLE
not An  issue but a suggestion for automatic proxy download 

### ISSUE THREAD

**Issue by harshpreets63** [LIL-JABA/valchecker#11]
download new proxies automatically on every task or when proxies end

**Comment by LIL-JABA** [comment]
where can i download them?

**Comment by harshpreets63** [comment]
> where can i download them?

There are many api/website to download new proxies everytime 
Like 
https://api.proxyscrape.com/?request=getproxies&proxytype=http&timeout=10000&country=all&ssl=all&anonymity=all

But i have heard that valorant checker needs some HIGHTECH ROCKET TECH proxies

**Comment by LIL-JABA** [comment]
yeah it needs uhq proxy 

but i'll try
