### ISSUE TITLE
older valchecker 3.4.1 says account is banned while 3.5.5 says it's not banned and valid

### ISSUE THREAD

**Issue by nerveywervy** [LIL-JABA/valchecker#18]
The valchecker v3.4.1 says an account
c4storzin:chicao10
is banned, but v.3.5.5 says it's not.
As well as this, proxies don't seem to work (I'm using the 3.4.1 proxies.)

**Comment by LIL-JABA** [comment]
proxies that come with checker don't work anymore. 

u can check the ban by urself to be sure but the latest version should be right (better ban checker)

**Comment by nerveywervy** [comment]
i removed the proxies but the 3.5.5 still counts banned accounts as valid including the one i sent here
should i instead download the one in the git directly?

**Comment by LIL-JABA** [comment]
i saw an error in the code, you are right. it marks perm banned accounts as valid. ty for reporting

**Comment by LIL-JABA** [comment]
fixed
