### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Drizkox** [LIL-JABA/valchecker#2]
doesnt hit 1 Valid acc

**Comment by LIL-JABA** [comment]
any errors or just marks it as invalid?

**Comment by Drizkox** [comment]
Ive checked valid acc for testing and it doesnt hit the valid acc

**Comment by LIL-JABA** [comment]
can u send me that account? (LIL JABA#1895) so I can check it because all my valid accounts are checked properly

**Comment by Drizkox** [comment]
skullCres:cu3162asdqwe31mizaµ
tejpata:Nayem91221
TakBlox19:Lionaraytak123
SoldadoFPS1:Davi00160596
sgtheero:Pasalepoako010811
keanekiller:Lhlanders123
HankoSalamo:enricetelias11
ecrind53:devranemine53
babamulo:md18052010@@
finwoob:delacruxMama1108!!!!!
Moonxaf1:1Moon3;4
ncgamerex:Utilization12!
dAaG503:Daagdenis28
kulestearian1:Sitamor1337
richardtrembala:88306828asd
davidmasteral:81703727Omega
gamal13l:cristian123
amarokrios:124124loko
Jawwaadd:mhamd2001
AhanisNoob:ahan@123
nicko1144:Vanessaj1144
hamzah652:hamzah-waqar
s4l4m4n:soyderiver1415
nahu184542:Nahu184542
pintordebanheiros:Metallicap3!
Omen6921:Korso0508
AKMancoX:Anmimelo123
molinic0:vegeta2000
KyzzeIcarus:jspigar1120
Isacachorra:anime123
shaqkingyt:Dec072006
fewtanapon:0874185446Za
rushxk:Xavvy123

**Comment by Drizkox** [comment]
all this + my personnal acc , but all are not hited , mb the keyword has changed

**Comment by LIL-JABA** [comment]
![image](https://user-images.githubusercontent.com/82034934/184529836-a49bf2c4-86c7-4d17-9724-cb7a75c9aca7.png)

all accounts work
