### ISSUE TITLE
getting errors no clue what the errors are

### ISSUE THREAD

**Issue by johans-eng** [LIL-JABA/valchecker#20]
![image](https://user-images.githubusercontent.com/62538631/188424444-311fe161-1d41-4850-a950-9c221f82bdac.png)
you need http proxys right??

**Comment by LIL-JABA** [comment]
u need uhq proxies to access the riot api. so if u don't have very good proxies, it would be better to use without proxy

**Comment by johans-eng** [comment]
How to use without proxies?

**Comment by LIL-JABA** [comment]
delete all proxies from proxy.txt

**Comment by johans-eng** [comment]
But you will get rate limited so you can check like 20 accs

**Comment by LIL-JABA** [comment]
yes but u need uhq proxy to bypass it

**Comment by johans-eng** [comment]
Howloang does ratelimit last

**Comment by johans-eng** [comment]
I can add a delta in settings of ik.correct

**Comment by LIL-JABA** [comment]
> Howloang does ratelimit last

default 30 seconds but u can edit it in settings

**Comment by johans-eng** [comment]
Yh but on the website

**Comment by johans-eng** [comment]
like howlong does a ratelimit last on riot

**Comment by LIL-JABA** [comment]
idk xd

**Comment by johans-eng** [comment]
aight

**Comment by johans-eng** [comment]
it gives 0 skins always u sure its working?

**Comment by LIL-JABA** [comment]
yes

**Comment by johans-eng** [comment]
hm k

**Comment by johans-eng** [comment]
where can you find version 3.6 bcs it says there is an update aviable

**Comment by LIL-JABA** [comment]
it's testing update rn

**Comment by johans-eng** [comment]
aight

**Comment by johans-eng** [comment]
58 valid but 0 skins i think that is wrong

**Comment by LIL-JABA** [comment]
if the region isn't unknown, it is 100% true

**Comment by johans-eng** [comment]
regions are in there like eu etc but its 0 skins in 59 accs kinda strange

**Comment by LIL-JABA** [comment]
> regions are in there like eu etc but its 0 skins in 59 accs kinda strange

u can log in this account and check

**Comment by johans-eng** [comment]
aight
