### ISSUE TITLE
checker says region is NA when it's LATAM

### ISSUE THREAD

**Issue by nerveywervy** [LIL-JABA/valchecker#21]
i feel like im annoying with these issues
but basically sometimes in the checker, it adds accounts to NA region but once you log in it's actually a LATAM account
not sure if its to do with the fact the first LATAM server near me is Chicago but yea
here's an example account
wiiroa123:wiiroa123

**Comment by LIL-JABA** [comment]
yeah, i know about this error. already fixed in v3.6.2

**Comment by LIL-JABA** [comment]
oh, i see, region checker still works incorrect. i'll release the fix tomorrow, ty for information
