### ISSUE TITLE
unranked account bug

### ISSUE THREAD

**Issue by nerveywervy** [LIL-JABA/valchecker#23]
most accounts that are level 2 or no level says the account is unranked when it is not.
ive seen accounts that do this for some reason and it seems like all accs do it very weird
however i did notice valorant replacing locked ranked with unranked so that might be the issue.

**Comment by LIL-JABA** [comment]
it just checks the level.  if it is less than 20, then the rank is locked.  and if it can't get the lvl (it happens), then it just checks the rank (blocked = unranked in riot games api)
