### ISSUE TITLE
Multi-Proxy does not work anymore

### ISSUE THREAD

**Issue by gamer99p** [LIL-JABA/valchecker#26]
Using a single proxy works, but not using multiple. I know it used to work with multi-proxy, but it does not anymore. Maybe it's because of riot, (probably) idk, hope yu can fix it anyways

**Comment by talscoom** [comment]
up

**Comment by LIL-JABA** [comment]
riot banned public proxies. buy them or use proxyless. ill probably fix on the future but idk when
