### ISSUE TITLE
Why doesn't the checker do anything?

### ISSUE THREAD

**Issue by EricPlayZ** [LIL-JABA/valchecker#27]
The checker doesn't seem to do anything after starting it, as seen in the picture below. It simply displays a response with a uri parameter and doesn't do anything afterwards. Every package is installed, obviously. Don't know what the issue could be.

![cmd_8hDnlcF0OR](https://user-images.githubusercontent.com/24963708/200189704-d41cd4f8-6057-4f06-98b3-6ce890a5a371.png)

**Comment by LIL-JABA** [comment]
replace `valcheckerfolder/src/codeparts/auth.py` with **https://dropmefiles.com/1xGzB**

**Comment by EricPlayZ** [comment]
Thanks, works fine now!
