### ISSUE TITLE
need help with auth

### ISSUE THREAD

**Issue by LIL-JABA** [LIL-JABA/valchecker#32]
I can't use threads with asyncio (I need asyncio because I use aiohttp). If anyone know how to fix it, **please open a pull request or contact me in discord**.

**Comment by Prodzify** [comment]
You can do it With requests too

**Comment by LIL-JABA** [comment]
I don't see methods I need in requests

**Comment by QuePast** [comment]
httpx should do the job if I understand the problem correctly

**Comment by QuePast** [comment]
nah that wont work, ignore :D

**Comment by Prodzify** [comment]
https://github.com/Prodzify/Valorant-auth

**Comment by LIL-JABA** [comment]
it doesn't work anymore
