### ISSUE TITLE
don't use proxies now. they do not work

### ISSUE THREAD

**Issue by lucash4x0r** [LIL-JABA/valchecker#35]
don't use proxies now. they do not work

_Originally posted by @LIL-JABA in https://github.com/LIL-JABA/valchecker/issues/34#issuecomment-1374577749_
      
any ETA on when it might get fixed ? too bad im not comfrortable with python to fix it myself.

edit: I was only trying to quote your comment lol, not open a whole ass new issue with it.

**Comment by liwe0** [comment]
yes proxies are no longer working

**Comment by LIL-JABA** [comment]
when I figure out how to fix #32
