### ISSUE TITLE
It doesnt work with a particular set of accounts

### ISSUE THREAD

**Issue by Legend-Recalls** [LIL-JABA/valchecker#43]
tried on asuka077:GokuBlack77
just doesnt work

**Comment by LIL-JABA** [comment]
it does work for me.
Your ip or proxy can be banned so it doesn't bypass cloudflare
also make sure you are using the latest version of checker

![image](https://user-images.githubusercontent.com/82034934/224991675-abd01ef2-0a74-4d61-b9af-7134ff277e46.png)

**Comment by Legend-Recalls** [comment]
its region is ap, plus the level is not 1 and it has sins, so basically it doesn't show the data

**Comment by LIL-JABA** [comment]
then this account has 2 regions. The checker does not know which region to check so it checks LOL region. In our case, LOL region is NA.

**Comment by Legend-Recalls** [comment]
so is it possible to add sth like that in checker so it checks both?

**Comment by LIL-JABA** [comment]
technically yes, it is possible. but I will not add it since it will have a huge impact on performance

**Comment by Legend-Recalls** [comment]
i see well i got this account after checking from other checker and I checked with this checker cause it looked hardwaorked. for some reason that checker gave correct results and if I be honest it didn't make a lot of speed difference even when it used proxy. nonetheless thankyou for replying.
