### ISSUE TITLE
thread is stuck 1 

### ISSUE THREAD

**Issue by muhammad110aa** [LIL-JABA/valchecker#45]
thread is stuck 1

**Comment by LIL-JABA** [comment]
I don't understand you. Give me more information about your problem.

**Comment by muhammad110aa** [comment]
![image](https://user-images.githubusercontent.com/126063811/226169115-48ade774-082e-48f2-b07a-50df4ebb2dbd.png)
 
 see it is in thread 1 cpm 1 . so slow

**Comment by muhammad110aa** [comment]
I cant change the thread to more or unlimited

**Comment by LIL-JABA** [comment]
Use better proxies for better cpm. You can choose threads before checking when it tells you to do that

**Comment by muhammad110aa** [comment]
it did not gave me any choice for threads

**Comment by LIL-JABA** [comment]
![image](https://user-images.githubusercontent.com/82034934/226187746-69f513cf-a648-47ca-a57e-a096be60e0dd.png)

**Comment by muhammad110aa** [comment]
it comes in proxy checker but not in val checker

**Comment by muhammad110aa** [comment]
![Uploading image.png…]()

**Comment by muhammad110aa** [comment]
![image](https://user-images.githubusercontent.com/126063811/226476027-a89e5b32-5e02-4976-b9d8-7dcdf0531c1a.png)

**Comment by LIL-JABA** [comment]
what is the problem here?
