### ISSUE TITLE
Proxy Checker Issue

### ISSUE THREAD

**Issue by Legend-Recalls** [LIL-JABA/valchecker#46]
I read faq, tried every type of proxy (http/https/socks4/socks5) but none of them seem to work.
proxyless checker works fine
but if I add proxies (I checked each one of them and they work)
it just doesn't do anything and keeps stalling
![image](https://user-images.githubusercontent.com/69719681/227920872-cacd11e6-fa59-4b14-9363-d7e080f91079.png)
did everything mentioned on the website

**Comment by LIL-JABA** [comment]
It checks if the checker can connect to your proxies or not. Since Riot bans public proxies, It DOES NOT guarantee they will work perfectly.

**Comment by Legend-Recalls** [comment]
can you give a single working proxy? because the ones I was using were premium ones, still not working I just need one so I can test?

**Comment by LIL-JABA** [comment]
I don't have any rn

**Comment by Legend-Recalls** [comment]
okay so i tried connect manually to the proxy and then running the checker proxyless and its working!
