### ISSUE TITLE
errno 2 no such file or directory why do i get this if i try to start ,,start,, ?

### ISSUE THREAD

**Issue by mu7st208** [LIL-JABA/valchecker#57]
errno 2 no such file or directory why do i get this if i try to start ,,star

**Comment by mu7st208** [comment]
![Screenshot 2024-01-14 010126](https://github.com/LIL-JABA/valchecker/assets/156510493/49c3a35d-4115-41ce-a1c8-31d7ac6484b6)
thats what i mean

**Comment by nokayee** [comment]
how did u fix
