### ISSUE TITLE
Not working in linux

### ISSUE THREAD

**Issue by SafwanAyyan** [LIL-JABA/valchecker#70]
The issue is that the windll module from ctypes is specific to Windows and is not available on Unix-based systems like Ubuntu.

**Comment by WeCanCodeTrust** [comment]
bc there was to little requests for linux support i wont no longer change the code so its natively supported maybe when im bored im gonna do it but its nothing we aiming for to achive

**Comment by LIL-JABA** [comment]
valchecker doesn't support linux
