### ISSUE TITLE
Not Working Getting Retries

### ISSUE THREAD

**Issue by md-gesan** [LIL-JABA/valchecker#75]
Proxies: 191 | Threads:  80 | Accounts: 844 | Checked 0/844
                [━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━] 0.00%

 ┏━ Main ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┏━━ Regions ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┏━━ Skins ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
 ┃ [>] Valid          >>:[0] (0.0%)    ┃ ┃ [>] EU            >>:[0]                 ┃ ┃ [>] 1-10            >>:[0]                            ┃
 ┃ [>] Banned         >>:[0]           ┃ ┃ [>] NA            >>:[0]                 ┃ ┃ [>] 10-20           >>:[0]                            ┃
 ┃ [>] TempBanned     >>:[0]           ┃ ┃ [>] AP            >>:[0]                 ┃ ┃ [>] 20-35           >>:[0]                            ┃
 ┃ [>] Errors         >>:[0]           ┃ ┃ [>] BR            >>:[0]                 ┃ ┃ [>] 35-40           >>:[0]                            ┃
 ┃ [>] Retries        >>:[1119]        ┃ ┃ [>] KR            >>:[0]                 ┃ ┃ [>] 40-70           >>:[0]                            ┃
 ┃                                     ┃ ┃ [>] LATAM         >>:[0]                 ┃ ┃ [>] 70-100          >>:[0]                            ┃
 ┃                                     ┃ ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ ┃ [>] 100-130         >>:[0]                            ┃
 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ ┏━━ Ranks ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┃ [>] 130-165         >>:[0]                            ┃
 ┏━ Not main ━━━━━━━━━━━━━━━━━━━━━━━━━━┓ ┃ [>] Unranked      >>:[0]                 ┃ ┃ [>] 165-200         >>:[0]                            ┃
 ┃ [>] With Skins       >>:[0]         ┃ ┃ [>] Iron          >>:[0]                 ┃ ┃ [>] 200+            >>:[0]                            ┃
 ┃ [>] Unverified Mail  >>:[0]         ┃ ┃ [>] Bronze        >>:[0]                 ┃ ┃                                                       ┃
 ┃ [>] Private          >>:[-1] (-1%)  ┃ ┃ [>] Silver        >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Gold          >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Platinum      >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Diamond       >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Ascendant     >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Immortal      >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Radiant       >>:[0]                 ┃ ┃                                                       ┃
 ┃                                     ┃ ┃ [>] Locked        >>:[0]                 ┃ ┃                                                       ┃
 ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
 Estimated remaining time: N/A

**Comment by LIL-JABA** [comment]
https://discord.gg/krMFTdSafD
