### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by LIL-JABA** [LIL-JABA/valchecker#8]
update the output interface

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-region-------> {reg}
-rank---------> {rank}
-level--------> {lvl}
-lastmatch---> {lastplayed}
-unverified mail-> {mailverif}
[ {skinscount} skins ]
{skins}
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

**Comment by PixelBlox** [comment]
yea i like it more
